name: "Notify Telegram"
description: "Get build notification to Telegram messenger"
author: yanzay
inputs:
  chat:
    description: "Chat to send: chat id or @channel_name"
    required: true
  token:
    description: "Telegram Bot token"
    required: true
  status:
    description: "Job status"
    required: true
runs:
  using: docker
  image: Dockerfile
branding:
  icon: send
  color: blue